googolplexTheater:
  appId: B1A3B99B
  heartbeatInterval: 5s
  heartbeatTimeout: 30s
  retryInterval: 15s
  devicesPath: /Users/jtyuzawa/Documents/personal_repos/googolplex-theater/build/install/googolplex-theater/conf/devices.yml
spring.application.name: googolplex-theater
spring.main.banner-mode: log