name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # LTS versions + latest
        java: [ '21' ]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - java: 22
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} on Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon -s build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.6.0
        if: ${{ matrix.java == '21' && matrix.os == 'ubuntu-latest' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "build/test-results/test/TEST-*.xml"
        if: always()
      - name: Save reports
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: reports-${{ matrix.os }}-${{ matrix.java }}
          path: build/reports/
